### ISSUE TITLE
./gradlew run  FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Sammers21** [vert-x3/vertx-gradle-starter#2]
hello, I have tried to get started with this template.

after 
```
$ git clone <repo link> && cd <repo> && ./gradlew run
```

I've got an error like:
![image](https://cloud.githubusercontent.com/assets/16746106/24325131/f1c6edca-11a3-11e7-91fa-9761b114c557.png)

Actually, I've got the same message after running 
```
curl http://vertx.io/assets/starter-scripts/create-vertx-project-gradle.sh -o vertx-create-gradle-project.sh; bash vertx-create-gradle-project.sh
```

any suggestions?

feel free to help me and ask any questions :)))

**Comment by cescoffier** [comment]
Did you try to launch it with —stacktrace, —info or —debug ? 

I just tried and it worked for me.

Clement

**Comment by Sammers21** [comment]
Sorry, the problem was is that gradlew used jdk9 as default, which is not well debugged.
